name: thimar_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  kiwi: ^4.1.0
  shared_preferences: ^2.2.1
  animate_do: ^3.0.2
  pin_code_fields: ^8.0.1
  circular_countdown_timer: ^0.2.3
  dotted_border: ^2.0.0+3
  carousel_slider: ^4.2.1
  flutter_html: ^3.0.0-alpha.5
  quick_log: ^5.3.0
  image_picker: ^1.0.4
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.3
  google_maps_flutter: ^2.3.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  share: ^2.0.4
  url_launcher: ^6.1.11
  lottie: ^2.3.2
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  get_it: ^7.6.0
  map_launcher: ^2.5.0+1
  flutter_local_notifications: ^17.1.2
  permission_handler: ^10.2.0
  app_settings: ^5.1.1
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/icons/appInputIcons/
    - assets/images/icons/accountIcons/
    - assets/images/icons/walletIcons/
    - assets/images/icons/addressIcons/
    - assets/images/icons/homeNavBarIcons/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
 
